### ISSUE TITLE
explore different types of datasets

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/team-assignment-team-4-1#2]
__Deliverable:__
- Bullet point summary of which datasets contain what type of data (calendar, neighborhoods, listings, ...)
- What's the historical availability of this data? How far can we go back?

**Comment by Lisa-Holling** [comment]
Airbnb in Barcelona

**Comment by Roosvansambeek** [comment]
See [Datasets_Info.R](https://github.com/course-dprep/team-assignment-team-4-1/blob/master/Datasets_Info.R) for the list of relevant datasets and relevant columns
